---
# apt module requires aptitude
- hosts: localhost
  become_method: sudo
  become: yes
  gather_facts: no
  tasks:
    - name: apt install docker
      apt: name='docker.io' state=latest
      register: aptout
    - debug: var=aptout
