--- # Loop Playbook example
- hosts: localhost
  become: yes
  become_user: root
  become_methon: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a list of users
      user: name={{ item }} state=present
      with_items:
        - user1
        - user2
        - user3
        - test
        - ansible
