--- # Run command once example
- hosts: all
  remote_user: root
  connection: ssh
  gather_facts: no
  tasks:
    - name: run cmd once on all hosts
      raw: /usr/bin/uptime >> /home/root/uptime.log
    - name: List var dir and log it
      raw: ls -al /var >> /home/root/vardir.list
      run_once: true

