--- # waitfor module
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks:
   - name: install tomcat
     action: yum name=tomcat state=installed
   - name: Waiting for port 8080 to Listen
     wait_for:
       port: 8080
       state: started
   - name: Verify lynx installation
     
